"use client";

import { motion } from "motion/react";
import {
    Dna,
    Terminal,
    GitBranch,
    Cpu,
    Database,
    ShieldCheck,
    LineChart
} from "lucide-react";
import LandingNavbar from "@/components/LandingNavbar";
import DnaBackground from "@/components/DnaBackground";
import Footer from "@/components/Footer";

export default function MethodologyPage() {
    return (
        <div className="min-h-screen bg-white">
            <DnaBackground />
            <LandingNavbar />

            <main className="pt-32 pb-20 px-8 w-full max-w-5xl mx-auto relative z-10">
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="space-y-4 mb-16"
                >
                    <span className="text-[10px] font-black uppercase tracking-[0.3em] text-primary">Technical Paper</span>
                    <h1 className="text-5xl md:text-7xl font-black text-text uppercase italic tracking-tighter leading-none">
                        Deterministic <br /> <span className="text-primary italic">Inference</span> Engine
                    </h1>
                    <p className="text-lg text-text-soft font-medium max-w-2xl leading-relaxed">
                        Our methodology leverages a rule-based deterministic engine to translate genotypic variants into quantitative clinical risk indices.
                    </p>
                </motion.div>

                <section className="grid grid-cols-1 md:grid-cols-2 gap-12">
                    <TechnicalBlock
                        icon={<Database className="size-5 text-primary" />}
                        title="Locus-Specific Alignment"
                        content="We process VCF files using a coordinate-based matching algorithm (GRCh38). By targeting specific chromosomal loci (e.g., Chromosome 22 for CYP2D6), we ensure 100% precision in variant extraction without the overhead of whole-genome parsing."
                    />
                    <TechnicalBlock
                        icon={<Cpu className="size-5 text-primary" />}
                        title="Diplotype Translation"
                        content="PharmaGuard utilizes Pharmacogene Variation (PharmVar) structural data. We map found SNPs to star-alleles (e.g., *1, *4, *10) and calculate the cumulative Activity Score (AS) ranging from 0 to 2.5."
                    />
                    <TechnicalBlock
                        icon={<Terminal className="size-5 text-primary" />}
                        title="Deterministic Mapping"
                        content="Unlike probabilistic models, our engine uses deterministic logic gates to map Activity Scores to phenotypes (PM, IM, NM, UM). This ensures zero hallucination and provides a legally verifiable clinical trail."
                    />
                    <TechnicalBlock
                        icon={<LineChart className="size-5 text-primary" />}
                        title="Risk Index Calculation"
                        content="The Clinical Risk Index is derived using a cross-matrix of Phenotype Severity and Drug-specific metabolic impact. Formula: Risk = (ActivityImpact * SeverityWeight) / ClinicalConstant."
                    />
                </section>

                <section className="mt-24 p-12 bg-primary rounded-[3rem] text-white relative overflow-hidden shadow-2xl">
                    <div className="absolute top-0 right-0 p-12 opacity-10">
                        <Dna size={300} strokeWidth={1} />
                    </div>
                    <div className="relative z-10 space-y-6">
                        <div className="flex items-center gap-3">
                            <ShieldCheck className="size-8 text-accent" />
                            <h2 className="text-3xl font-black uppercase italic tracking-tighter">Clinical Validation</h2>
                        </div>
                        <p className="text-lg text-white/80 font-medium max-w-3xl leading-relaxed">
                            Every assessment generated by PharmaGuard is cross-referenced with CPIC (Clinical Pharmacogenetics Implementation Consortium) level A/B guidelines. We prioritize safety by applying a conservative heuristic when ambiguous diplotypes are encountered.
                        </p>
                        <div className="flex flex-wrap gap-8 pt-6">
                            <div className="flex flex-col">
                                <span className="text-[10px] font-black uppercase tracking-widest text-accent/60 mb-2">Data Source</span>
                                <span className="text-xl font-black italic">PharmGKB v2026</span>
                            </div>
                            <div className="flex flex-col">
                                <span className="text-[10px] font-black uppercase tracking-widest text-accent/60 mb-2">Accuracy</span>
                                <span className="text-xl font-black italic">±0.001 Logic Error</span>
                            </div>
                            <div className="flex flex-col">
                                <span className="text-[10px] font-black uppercase tracking-widest text-accent/60 mb-2">Protocol</span>
                                <span className="text-xl font-black italic">GRCh38 / hG38</span>
                            </div>
                        </div>
                    </div>
                </section>
            </main>

            <Footer />
        </div>
    );
}

function TechnicalBlock({ icon, title, content }: { icon: any, title: string, content: string }) {
    return (
        <motion.div
            initial={{ opacity: 0, x: -20 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            className="space-y-4"
        >
            <div className="flex items-center gap-3">
                <div className="p-2 bg-primary/5 rounded-lg border border-primary/10">
                    {icon}
                </div>
                <h3 className="text-lg font-black uppercase italic tracking-tight text-text">{title}</h3>
            </div>
            <p className="text-sm text-text-soft leading-relaxed font-medium">
                {content}
            </p>
        </motion.div>
    );
}
